# Generated by Django 3.0.6 on 2020-06-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
