# Generated by Django 3.0.6 on 2020-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200616_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
