# Generated by Django 3.0.6 on 2020-06-17 03:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200617_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portrait',
            field=imagekit.models.fields.ProcessedImageField(upload_to='portrait/%Y%m%d'),
        ),
    ]
