# Generated by Django 3.0.6 on 2020-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basicinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('edubg', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('birthplace', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('wechat', models.CharField(max_length=100)),
            ],
        ),
    ]
