# Generated by Django 3.0.6 on 2020-06-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_certificate_selfcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduexperience',
            name='major',
            field=models.CharField(default='school', max_length=100),
        ),
    ]
